### ISSUE TITLE
[Client] 게시판 기능 구현

### ISSUE THREAD

**Issue by devMinGyu** [codestates/conimals#103]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 게시판 기능 구현

### TODO
1. [x] 게시판 리스트 페이지
2. [x] 새로운 글 작성 페이지
3. [x] 리스트 페이지에서 작성된 글 누르면 볼 수 있는 페이지
4. [x] 서버와 통신 및 데이터 주고받기

### Labels
- Estimated time: `E: 3d`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
