### ISSUE TITLE
[Client] 게시판 CSS 작업

### ISSUE THREAD

**Issue by devMinGyu** [codestates/conimals#126]
### ISSUE
- Group:  `client`
- Type: `design`
- Detail: 게시판 디자인 작업

### TODO
1. [x] 전체 게시글 보는 페이지 디자인
2. [x] 글쓰기 및 수정 페이지 디자인
3. [x] 게시물 상세보기 페이지 디자인

### Labels
- Estimated time: `E: 5h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `Middle`
