### ISSUE TITLE
[server - task] 게시글 좋아요 기능 구현

### ISSUE THREAD

**Issue by YeonSeoJo** [codestates/conimals#134]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: 게시물에 좋아요 표시 기능 및, 내가 좋아요 한 게시물 확인

### TODO
1. [ ] likes 모델 생성 및 연결
2. [ ] 게시물에 좋아요 버튼을 누르면 게시물에 표시
3. [ ] 마이페이지에서 내가 좋아요 버튼을 클릭한 게시물 목록을 확인
4. [ ] 이미 좋아요를 한 게시물에서 다시 좋아요를 클릭하면, 좋아요 상태 해제

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `server`
- Sprint: `Sprint__NUMBER__3`
- Urgency: `Middle`
