### ISSUE TITLE
[Client] 적합도 테스트 결과 페이지 만들기

### ISSUE THREAD

**Issue by kitch-finn** [codestates/conimals#24]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 적합도 테스트 결과 페이지 만들기

### TODO
1. [x] 적합도 테스트 결과 페이지 만들기 1~3
2. [x] 최종 점수에 따라 다른 페이지로의 랜딩 구현
3. [x] Map 페이지로 링크되는 버튼 구현

### Labels
- Estimated time: `E: 5h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
